language: node_js
-env:
    - CXX=g++-4.8
node_js:
    - '12'
branches:
    only:
        - dependencies-update
        - master
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
script:
    - npm test
after_success:
    - npm run codecov
